export const USER_MAP = [
  {
    password: "Admin!23",
    pernr: "00000000",
    nama: "John Doe",
    personal_area: "PA01",
    desc_personal_area: "Head Office",
    personal_area_pgs: "PG01",
    desc_personal_area_pgs: "Head Office PGS",
    personal_subarea: "PS01",
    desc_personal_subarea: "IT Department",
    personal_subarea_pgs: "PSPG01",
    desc_personal_subarea_pgs: "IT Department PGS",
    cost_center: "CC123",
    desc_cost_center: "Cost Center 123",
    cost_center_pgs: "CCPG123",
    desc_cost_center_pgs: "Cost Center PGS 123",
    organisasi_unit: "OU01",
    desc_organisasi_unit: "Organizational Unit 1",
    organisasi_unit_pgs: "OUPG01",
    desc_organisasi_unit_pgs: "Organizational Unit PGS 1",
    jabatan: "Admin Manager",
    jgpg: "Grade 5",
    nip: "NIP123456",
    hilfm: "H01",
    htext: "Text H01",
    hilfm_pgs: "H01PG",
    htext_pgs: "Text H01 PGS",
    stell: "ST01",
    stell_tx: "Position ST01",
    plans: "PL01",
    plans_tx: "Plan PL01",
    plans_pgs: "PL01PG",
    plans_pgs_tx: "Plan PL01 PGS",
    eselon: "E1",
    tipe_uker: "Permanent",
    admin: "Yes",
    jenkel: "Male",
    tempat_lahir: "Jakarta",
    tmtpt: "2020-01-01",
    tmtmasuk: "2019-01-01",
    persk: "P01",
    branch_code: "BC01",
    branch_code_pgs: "BCPG01",
    tipe_pekerja: "Full-Time",
    id_corporate_title: "CT01",
    corporate_title: "Corporate Title 1",
    id_corporate_title_ori: "CTO01",
    corporate_title_ori: "Corporate Title Original 1",
    add_area: "Area 1",
    status_pekerja: "Active",
  },
  {
    password: "Admin!23",
    pernr: "00000001",
    nama: "John Doe",
    personal_area: "PA01",
    desc_personal_area: "Head Office",
    personal_area_pgs: "PG01",
    desc_personal_area_pgs: "Head Office PGS",
    personal_subarea: "PS01",
    desc_personal_subarea: "IT Department",
    personal_subarea_pgs: "PSPG01",
    desc_personal_subarea_pgs: "IT Department PGS",
    cost_center: "CC123",
    desc_cost_center: "Cost Center 123",
    cost_center_pgs: "CCPG123",
    desc_cost_center_pgs: "Cost Center PGS 123",
    organisasi_unit: "OU01",
    desc_organisasi_unit: "Organizational Unit 1",
    organisasi_unit_pgs: "OUPG01",
    desc_organisasi_unit_pgs: "Organizational Unit PGS 1",
    jabatan: "SEO Specialist",
    jgpg: "Grade 5",
    nip: "NIP123456",
    hilfm: "H01",
    htext: "Text H01",
    hilfm_pgs: "H01PG",
    htext_pgs: "Text H01 PGS",
    stell: "ST01",
    stell_tx: "Position ST01",
    plans: "PL01",
    plans_tx: "Plan PL01",
    plans_pgs: "PL01PG",
    plans_pgs_tx: "Plan PL01 PGS",
    eselon: "E1",
    tipe_uker: "Permanent",
    admin: "Yes",
    jenkel: "Male",
    tempat_lahir: "Jakarta",
    tmtpt: "2020-01-01",
    tmtmasuk: "2019-01-01",
    persk: "P01",
    branch_code: "BC01",
    branch_code_pgs: "BCPG01",
    tipe_pekerja: "Full-Time",
    id_corporate_title: "CT01",
    corporate_title: "Corporate Title 1",
    id_corporate_title_ori: "CTO01",
    corporate_title_ori: "Corporate Title Original 1",
    add_area: "Area 1",
    status_pekerja: "Active",
  },
  {
    password: "Admin!23",
    pernr: "00000002",
    nama: "John Doe",
    personal_area: "PA01",
    desc_personal_area: "Head Office",
    personal_area_pgs: "PG01",
    desc_personal_area_pgs: "Head Office PGS",
    personal_subarea: "PS01",
    desc_personal_subarea: "IT Department",
    personal_subarea_pgs: "PSPG01",
    desc_personal_subarea_pgs: "IT Department PGS",
    cost_center: "CC123",
    desc_cost_center: "Cost Center 123",
    cost_center_pgs: "CCPG123",
    desc_cost_center_pgs: "Cost Center PGS 123",
    organisasi_unit: "OU01",
    desc_organisasi_unit: "Organizational Unit 1",
    organisasi_unit_pgs: "OUPG01",
    desc_organisasi_unit_pgs: "Organizational Unit PGS 1",
    jabatan: "Manajer SEO",
    jgpg: "Grade 5",
    nip: "NIP123456",
    hilfm: "H01",
    htext: "Text H01",
    hilfm_pgs: "H01PG",
    htext_pgs: "Text H01 PGS",
    stell: "ST01",
    stell_tx: "Position ST01",
    plans: "PL01",
    plans_tx: "Plan PL01",
    plans_pgs: "PL01PG",
    plans_pgs_tx: "Plan PL01 PGS",
    eselon: "E1",
    tipe_uker: "Permanent",
    admin: "Yes",
    jenkel: "Male",
    tempat_lahir: "Jakarta",
    tmtpt: "2020-01-01",
    tmtmasuk: "2019-01-01",
    persk: "P01",
    branch_code: "BC01",
    branch_code_pgs: "BCPG01",
    tipe_pekerja: "Full-Time",
    id_corporate_title: "CT01",
    corporate_title: "Corporate Title 1",
    id_corporate_title_ori: "CTO01",
    corporate_title_ori: "Corporate Title Original 1",
    add_area: "Area 1",
    status_pekerja: "Active",
  },
  {
    password: "Admin!23",
    pernr: "00000003",
    nama: "John Doe",
    personal_area: "PA01",
    desc_personal_area: "Head Office",
    personal_area_pgs: "PG01",
    desc_personal_area_pgs: "Head Office PGS",
    personal_subarea: "PS01",
    desc_personal_subarea: "IT Department",
    personal_subarea_pgs: "PSPG01",
    desc_personal_subarea_pgs: "IT Department PGS",
    cost_center: "CC123",
    desc_cost_center: "Cost Center 123",
    cost_center_pgs: "CCPG123",
    desc_cost_center_pgs: "Cost Center PGS 123",
    organisasi_unit: "OU01",
    desc_organisasi_unit: "Organizational Unit 1",
    organisasi_unit_pgs: "OUPG01",
    desc_organisasi_unit_pgs: "Organizational Unit PGS 1",
    jabatan: "QA SEO",
    jgpg: "Grade 5",
    nip: "NIP123456",
    hilfm: "H01",
    htext: "Text H01",
    hilfm_pgs: "H01PG",
    htext_pgs: "Text H01 PGS",
    stell: "ST01",
    stell_tx: "Position ST01",
    plans: "PL01",
    plans_tx: "Plan PL01",
    plans_pgs: "PL01PG",
    plans_pgs_tx: "Plan PL01 PGS",
    eselon: "E1",
    tipe_uker: "Permanent",
    admin: "Yes",
    jenkel: "Male",
    tempat_lahir: "Jakarta",
    tmtpt: "2020-01-01",
    tmtmasuk: "2019-01-01",
    persk: "P01",
    branch_code: "BC01",
    branch_code_pgs: "BCPG01",
    tipe_pekerja: "Full-Time",
    id_corporate_title: "CT01",
    corporate_title: "Corporate Title 1",
    id_corporate_title_ori: "CTO01",
    corporate_title_ori: "Corporate Title Original 1",
    add_area: "Area 1",
    status_pekerja: "Active",
  },
];

export async function POST(request: Request) {
  const body = await request.json(); // res now contains body
  const { username, password } = body;
  const foundUser = USER_MAP.find((it) => it.pernr === username);

  if (!foundUser) {
    Response.error();
    return Response.json({ error: "User not found" }, { status: 401 });
  }

  return Response.json({ message: "Success, welcome" });
}
